name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün çalıştır
  workflow_dispatch: 

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: T-vulpes
          year_range: 2025
          outputs: |
            dark_mode: output/github-contribution-grid-snake-dark.svg
            light_mode: output/github-contribution-grid-snake.svg
          color_snake: white    # Yılan rengi beyaz
          color_dots: white     # Noktaların rengi beyaz
          color_empty: transparent  # Boş alanlar saydam

      - name: Push the Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output  # Çıktıyı doğru klasöre yönlendir
