name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: T-vulpes
          year_range: 2025

      - name: Push the Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
